/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IHeroMandate {
    function createMandate(address agent, uint64 expiry, bytes32 scope_root, bytes32 model_hash) external payable returns (uint256);

    function delegate(uint256 parent_id, address agent, uint256 amount, uint64 expiry, bytes32 scope_root, bytes32 model_hash) external returns (uint256);

    function execute(uint256 id, bytes32 instrument, uint256 amount, bytes32[][] memory proofs) external returns (bool);

    function reclaim(uint256 id) external;

    function getMandate(uint256 id) external view returns (uint256, address, uint256, uint64, bytes32, bytes32, bytes32, uint64);

    function mandateCount() external view returns (uint256);

    function capacityOf(uint256 id) external view returns (uint256);
}
